default_stages: [commit, manual]
exclude: "CHANGELOG.md"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      # - id: no-commit-to-branch
      #   args: ['-b master']
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.3
    hooks:
      - id: yamllint
  # - repo: https://github.com/executablebooks/mdformat
  #   rev: 0.7.14
  #   hooks:
  #     - id: mdformat
  #       additional_dependencies:
  #         - mdformat-gfm
  #         - mdformat-tables
  #       exclude: ^docs\/(changelog|contributing|license|readme|actions\/(pre-commit))\.md$
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v8.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
  # - repo: https://github.com/sqlfluff/sqlfluff
  #   rev: 0.13.2
  #   hooks:
  #   - id: sqlfluff-lint
  # - repo: https://github.com/rhysd/actionlint
  #   rev: v1.6.13
  #   hooks:
  #     - id: actionlint-docker
