# To run:
# docker compose up
# docker compose exec db psql -v ON_ERROR_STOP=1 --username postgres

version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-example}'
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:

  data:
